name = "lustre_omnistate"
version = "0.0.3"
target = "javascript"

description = "Use Remote State, Locally"
repository = { type = "github", user = "weedonandscott", repo = "lustre_omnistate" }
licences = ["MIT"]

internal_modules = ["internal", "internal/*"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
lustre = ">= 4.6.1 and < 5.0.0"
lustre_websocket = ">= 0.7.6 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
